apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps.yaml
  - infrastructure.yaml

configMapGenerator:
  - name: cluster-vars
    envs:
      - environment.env
generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
  - nginx-patch.yaml
