apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  values:
    image:
      registry: docker.io
      repository: bitnami/nginx-ingress-controller
      tag: latest